AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  Env:
    Type: String
    Default: 'qa1'
    AllowedValues:
      - 'qa1'
      - 'qa2'
      - 'qa5'
Resources: 
  plylambda: 
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: !Sub "ply-${Env}-lambda"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "lambda:InvokeFunction"
            Resource: 
              - !Sub "arn:aws:lambda:ap-northeast-1:${AWS::AccountId}:function:${Env}-lm-*-rt-*"
          - Effect: "Allow"
            Action:
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: 
              - !Sub "arn:aws:logs:ap-northeast-1:${AWS::AccountId}:log-group:/aws/lambda/${Env}-lm-*-rt-*"
          - Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
            Resource: 
              - !Sub "arn:aws:logs:ap-northeast-1:${AWS::AccountId}:*"